export enum Role {
  ADMIN = 'ADMIN',
  DEPARTMENT_MANAGER = 'DEPARTMENT_MANAGER',
  GENERAL = 'GENERAL'
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  RETIRED = 'RETIRED'
}

export enum SkillLevel {
  A = 'A',
  B = 'B',
  C = 'C',
  UNEVALUATED = 'UNEVALUATED'
}

export enum EvaluationType {
  SELF = 'SELF',
  MANAGER = 'MANAGER'
}

export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE = 'EMPLOYEE_DELETE',
  
  DEPARTMENT_CREATE = 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE = 'DEPARTMENT_DELETE',
  
  SKILL_CREATE = 'SKILL_CREATE',
  SKILL_UPDATE = 'SKILL_UPDATE',
  SKILL_DELETE = 'SKILL_DELETE',
  
  SKILL_EVALUATION_SELF = 'SKILL_EVALUATION_SELF',
  SKILL_EVALUATION_MANAGER = 'SKILL_EVALUATION_MANAGER',
  
  CERTIFICATION_CREATE = 'CERTIFICATION_CREATE',
  CERTIFICATION_UPDATE = 'CERTIFICATION_UPDATE',
  CERTIFICATION_DELETE = 'CERTIFICATION_DELETE',
  CERTIFICATION_ATTACHMENT_UPLOAD = 'CERTIFICATION_ATTACHMENT_UPLOAD',
  CERTIFICATION_ATTACHMENT_DELETE = 'CERTIFICATION_ATTACHMENT_DELETE',
  
  WORK_HISTORY_CREATE = 'WORK_HISTORY_CREATE',
  WORK_HISTORY_UPDATE = 'WORK_HISTORY_UPDATE',
  WORK_HISTORY_DELETE = 'WORK_HISTORY_DELETE'
}

export enum TargetType {
  ACCOUNT = 'ACCOUNT',
  EMPLOYEE = 'EMPLOYEE',
  DEPARTMENT = 'DEPARTMENT',
  SKILL = 'SKILL',
  SKILL_EVALUATION = 'SKILL_EVALUATION',
  CERTIFICATION = 'CERTIFICATION',
  CERTIFICATION_ATTACHMENT = 'CERTIFICATION_ATTACHMENT',
  WORK_HISTORY = 'WORK_HISTORY',
  SYSTEM = 'SYSTEM'
}
